/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import "@carbon/ai-chat/dist/es/web-components/cds-aichat-container/index.js";
import "./history-writeable-element-example";

import {
  BusEventType,
  type ChatInstance,
  type MessageResponse,
  type PublicConfig,
  type UserDefinedItem,
} from "@carbon/ai-chat";
import { html, LitElement, css } from "lit";
import { customElement, state } from "lit/decorators.js";

import { customSendMessage } from "./customSendMessage";
import { customLoadHistory } from "./customLoadHistory";

interface UserDefinedSlotsMap {
  [key: string]: UserDefinedSlot;
}

interface UserDefinedSlot {
  message: UserDefinedItem;
  fullMessage: MessageResponse;
}

const config: PublicConfig = {
  history: {
    isOn: true,
  },
  messaging: {
    customSendMessage,
    customLoadHistory,
  },
};

@customElement("my-app")
export class Demo extends LitElement {
  static styles = css`
    .external {
      background: green;
      color: #fff;
      padding: 1rem;
    }
  `;

  @state()
  accessor instance!: ChatInstance;

  @state()
  accessor activeResponseId: string | null = null;

  @state()
  accessor workspaceType: string | null = null;

  @state()
  accessor workspaceId: string | undefined = undefined;

  @state()
  accessor workspaceAdditionalData: any = null;

  @state()
  accessor userDefinedSlotsMap: UserDefinedSlotsMap = {};

  @state()
  accessor valueFromParent: string = Date.now().toString();

  onBeforeRender = (instance: ChatInstance) => {
    // Set the instance in state.
    this.instance = instance;
    const initialState = instance.getState();
    this.activeResponseId = initialState.activeResponseId ?? null;

    // Register user defined response handler.
    instance.on({
      type: BusEventType.USER_DEFINED_RESPONSE,
      handler: this.userDefinedHandler,
    });
  };

  /**
   * Handles loading a new chat history.
   */
  _loadChat = async (event: CustomEvent) => {
    if (!this.instance) {
      return;
    }
    const requestText = event.detail.chatName;
    const historyData = await customLoadHistory(this.instance, requestText);

    await this.instance.messaging.clearConversation();
    this.instance.messaging.insertHistory(historyData);
  };

  /**
   * Handles when the workspace panel is about to open.
   */
  workspacePanelPreOpenHandler = (event: any) => {
    console.log(event, "Workspace panel pre-open");
  };

  /**
   * Handles when the workspace panel is opened.
   */
  workspacePanelOpenHandler = (event: any) => {
    console.log(event, "Workspace panel opened");

    // Extract workspace data from the event
    const { workspaceId, additionalData } = event.data;
    this.workspaceId = workspaceId;
    this.workspaceAdditionalData = additionalData;
    this.workspaceType = (additionalData as { type?: string })?.type || null;
  };

  /**
   * Handles when the workspace panel is closed.
   */
  workspacePanelCloseHandler = (event: any) => {
    console.log(event, "Workspace panel closed");

    // Clear workspace data when panel closes
    this.workspaceType = null;
    this.workspaceId = undefined;
    this.workspaceAdditionalData = null;
  };

  /**
   * Each user defined event is tied to a slot deeply rendered with-in AI chat that is generated at runtime.
   * Here we make sure we store all these slots along with their relevant data in order to be able to dynamically
   * render the content to be slotted when this.renderUserDefinedSlots() is called in the render function.
   */
  userDefinedHandler = (event: any) => {
    const { data } = event;
    this.userDefinedSlotsMap[data.slot] = {
      message: data.message,
      fullMessage: data.fullMessage,
    };
    this.requestUpdate();
  };

  /**
   * This renders each of the dynamically generated slots that were generated by the AI chat by calling
   * this.renderUserDefinedResponse on each one.
   */
  renderUserDefinedSlots() {
    const userDefinedSlotsKeyArray = Object.keys(this.userDefinedSlotsMap);
    return userDefinedSlotsKeyArray.map((slot) => {
      return this.renderUserDefinedResponse(slot);
    });
  }

  /**
   * Here we process a single item from this.userDefinedSlotsMap. We go ahead and use a switch statement to decide
   * which element we should be rendering.
   */
  renderUserDefinedResponse(slot: keyof UserDefinedSlotsMap) {
    const slotData = this.userDefinedSlotsMap[slot];
    if (!slotData) {
      return null;
    }

    const { message, fullMessage } = slotData;

    const userDefinedMessage = message;
    const isLatest =
      Boolean(this.activeResponseId) &&
      fullMessage?.id === this.activeResponseId;

    // Check the "type" we have used as our key.
    switch (userDefinedMessage.user_defined?.user_defined_type) {
      case "my_unique_identifier":
        // And here is an example using your own component.
        return html`<div slot=${slot}>
          <div class="external">
            ${userDefinedMessage.user_defined.text as string}
            <div>
              Latest response id:
              ${this.activeResponseId ? this.activeResponseId : "none yet"}
            </div>
            <div>
              Is this the most recent message? ${isLatest ? "Yes" : "Nope"}
            </div>
          </div>
        </div>`;
      default:
        return null;
    }
  }

  renderWriteableElementSlots() {
    if (!this.instance) {
      return null;
    }

    const key = "historyPanelElement";

    return html`
      <div slot=${key}>
        <history-writeable-element-example
          location=${key}
          .instance=${this.instance}
          .valueFromParent=${this.valueFromParent}
          .isMobile=${
            this.instance?.getState().customPanels.history.isMobile ?? false
          }
          @history-panel-load-chat=${this._loadChat}
        ></history-writeable-element-example>
      </div>
    `;
  }

  render() {
    return html`
      <cds-aichat-container
        .config=${config}
        .onBeforeRender=${this.onBeforeRender}
        >${this.renderUserDefinedSlots()}${this.renderWriteableElementSlots()}</cds-aichat-container
      >
    `;
  }
}
